package com.tomcat.dao.impl;

import com.tomcat.dao.BorrowTransferDAO;
import com.tomcat.model.BorrowTransfer;
import com.tomcat.model.BorrowTransferExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BorrowTransferDAOImpl extends SqlMapClientDaoSupport implements BorrowTransferDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public BorrowTransferDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(BorrowTransferExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("borrow_transfer.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(BorrowTransferExample example) {
        int rows = getSqlMapClientTemplate().delete("borrow_transfer.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        BorrowTransfer key = new BorrowTransfer();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("borrow_transfer.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(BorrowTransfer record) {
        getSqlMapClientTemplate().insert("borrow_transfer.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(BorrowTransfer record) {
        getSqlMapClientTemplate().insert("borrow_transfer.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(BorrowTransferExample example) {
        List list = getSqlMapClientTemplate().queryForList("borrow_transfer.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public BorrowTransfer selectByPrimaryKey(Integer id) {
        BorrowTransfer key = new BorrowTransfer();
        key.setId(id);
        BorrowTransfer record = (BorrowTransfer) getSqlMapClientTemplate().queryForObject("borrow_transfer.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(BorrowTransfer record, BorrowTransferExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("borrow_transfer.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(BorrowTransfer record, BorrowTransferExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("borrow_transfer.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(BorrowTransfer record) {
        int rows = getSqlMapClientTemplate().update("borrow_transfer.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(BorrowTransfer record) {
        int rows = getSqlMapClientTemplate().update("borrow_transfer.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table borrow_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends BorrowTransferExample {
        private Object record;

        public UpdateByExampleParms(Object record, BorrowTransferExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}