package com.tomcat.dao.impl;

import com.tomcat.dao.TbAuthAssignmentDAO;
import com.tomcat.model.TbAuthAssignment;
import com.tomcat.model.TbAuthAssignmentExample;
import com.tomcat.model.TbAuthAssignmentKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbAuthAssignmentDAOImpl extends SqlMapClientDaoSupport implements TbAuthAssignmentDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbAuthAssignmentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbAuthAssignmentExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_auth_assignment.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbAuthAssignmentExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_auth_assignment.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(TbAuthAssignmentKey key) {
        int rows = getSqlMapClientTemplate().delete("tb_auth_assignment.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbAuthAssignment record) {
        getSqlMapClientTemplate().insert("tb_auth_assignment.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbAuthAssignment record) {
        getSqlMapClientTemplate().insert("tb_auth_assignment.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(TbAuthAssignmentExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_auth_assignment.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbAuthAssignment selectByPrimaryKey(TbAuthAssignmentKey key) {
        TbAuthAssignment record = (TbAuthAssignment) getSqlMapClientTemplate().queryForObject("tb_auth_assignment.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbAuthAssignment record, TbAuthAssignmentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_auth_assignment.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbAuthAssignment record, TbAuthAssignmentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_auth_assignment.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbAuthAssignment record) {
        int rows = getSqlMapClientTemplate().update("tb_auth_assignment.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbAuthAssignment record) {
        int rows = getSqlMapClientTemplate().update("tb_auth_assignment.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_auth_assignment
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbAuthAssignmentExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbAuthAssignmentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}