package com.tomcat.dao.impl;

import com.tomcat.dao.TbAuthItemDAO;
import com.tomcat.model.TbAuthItem;
import com.tomcat.model.TbAuthItemExample;
import com.tomcat.model.TbAuthItemWithBLOBs;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbAuthItemDAOImpl extends SqlMapClientDaoSupport implements TbAuthItemDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbAuthItemDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbAuthItemExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_auth_item.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbAuthItemExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_auth_item.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(String name) {
        TbAuthItem key = new TbAuthItem();
        key.setName(name);
        int rows = getSqlMapClientTemplate().delete("tb_auth_item.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbAuthItemWithBLOBs record) {
        getSqlMapClientTemplate().insert("tb_auth_item.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbAuthItemWithBLOBs record) {
        getSqlMapClientTemplate().insert("tb_auth_item.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExampleWithBLOBs(TbAuthItemExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_auth_item.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExampleWithoutBLOBs(TbAuthItemExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_auth_item.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbAuthItemWithBLOBs selectByPrimaryKey(String name) {
        TbAuthItem key = new TbAuthItem();
        key.setName(name);
        TbAuthItemWithBLOBs record = (TbAuthItemWithBLOBs) getSqlMapClientTemplate().queryForObject("tb_auth_item.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbAuthItemWithBLOBs record, TbAuthItemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_auth_item.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbAuthItemWithBLOBs record, TbAuthItemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_auth_item.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbAuthItem record, TbAuthItemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_auth_item.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbAuthItemWithBLOBs record) {
        int rows = getSqlMapClientTemplate().update("tb_auth_item.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbAuthItemWithBLOBs record) {
        int rows = getSqlMapClientTemplate().update("tb_auth_item.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbAuthItem record) {
        int rows = getSqlMapClientTemplate().update("tb_auth_item.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbAuthItemExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbAuthItemExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}