package com.tomcat.dao.impl;

import com.tomcat.dao.TbBorrowWishDAO;
import com.tomcat.model.TbBorrowWish;
import com.tomcat.model.TbBorrowWishExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbBorrowWishDAOImpl extends SqlMapClientDaoSupport implements TbBorrowWishDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbBorrowWishDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbBorrowWishExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_borrow_wish.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbBorrowWishExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_borrow_wish.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        TbBorrowWish key = new TbBorrowWish();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_borrow_wish.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbBorrowWish record) {
        getSqlMapClientTemplate().insert("tb_borrow_wish.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbBorrowWish record) {
        getSqlMapClientTemplate().insert("tb_borrow_wish.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(TbBorrowWishExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_borrow_wish.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbBorrowWish selectByPrimaryKey(Integer id) {
        TbBorrowWish key = new TbBorrowWish();
        key.setId(id);
        TbBorrowWish record = (TbBorrowWish) getSqlMapClientTemplate().queryForObject("tb_borrow_wish.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbBorrowWish record, TbBorrowWishExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_borrow_wish.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbBorrowWish record, TbBorrowWishExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_borrow_wish.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbBorrowWish record) {
        int rows = getSqlMapClientTemplate().update("tb_borrow_wish.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbBorrowWish record) {
        int rows = getSqlMapClientTemplate().update("tb_borrow_wish.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_borrow_wish
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbBorrowWishExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbBorrowWishExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}