package com.tomcat.dao.impl;

import com.tomcat.dao.TbFlowOrderDAO;
import com.tomcat.model.TbFlowOrder;
import com.tomcat.model.TbFlowOrderExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbFlowOrderDAOImpl extends SqlMapClientDaoSupport implements TbFlowOrderDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbFlowOrderDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbFlowOrderExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_flow_order.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbFlowOrderExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_flow_order.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        TbFlowOrder key = new TbFlowOrder();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_flow_order.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbFlowOrder record) {
        getSqlMapClientTemplate().insert("tb_flow_order.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbFlowOrder record) {
        getSqlMapClientTemplate().insert("tb_flow_order.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(TbFlowOrderExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_flow_order.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbFlowOrder selectByPrimaryKey(Integer id) {
        TbFlowOrder key = new TbFlowOrder();
        key.setId(id);
        TbFlowOrder record = (TbFlowOrder) getSqlMapClientTemplate().queryForObject("tb_flow_order.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbFlowOrder record, TbFlowOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_flow_order.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbFlowOrder record, TbFlowOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_flow_order.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbFlowOrder record) {
        int rows = getSqlMapClientTemplate().update("tb_flow_order.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbFlowOrder record) {
        int rows = getSqlMapClientTemplate().update("tb_flow_order.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_flow_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbFlowOrderExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbFlowOrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}