package com.tomcat.dao.impl;

import com.tomcat.dao.TbHongbaoSettingDAO;
import com.tomcat.model.TbHongbaoSetting;
import com.tomcat.model.TbHongbaoSettingExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbHongbaoSettingDAOImpl extends SqlMapClientDaoSupport implements TbHongbaoSettingDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbHongbaoSettingDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbHongbaoSettingExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_hongbao_setting.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbHongbaoSettingExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_hongbao_setting.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        TbHongbaoSetting key = new TbHongbaoSetting();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_hongbao_setting.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbHongbaoSetting record) {
        getSqlMapClientTemplate().insert("tb_hongbao_setting.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbHongbaoSetting record) {
        getSqlMapClientTemplate().insert("tb_hongbao_setting.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(TbHongbaoSettingExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_hongbao_setting.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbHongbaoSetting selectByPrimaryKey(Integer id) {
        TbHongbaoSetting key = new TbHongbaoSetting();
        key.setId(id);
        TbHongbaoSetting record = (TbHongbaoSetting) getSqlMapClientTemplate().queryForObject("tb_hongbao_setting.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbHongbaoSetting record, TbHongbaoSettingExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_hongbao_setting.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbHongbaoSetting record, TbHongbaoSettingExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_hongbao_setting.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbHongbaoSetting record) {
        int rows = getSqlMapClientTemplate().update("tb_hongbao_setting.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbHongbaoSetting record) {
        int rows = getSqlMapClientTemplate().update("tb_hongbao_setting.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_hongbao_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbHongbaoSettingExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbHongbaoSettingExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}