package com.tomcat.dao.impl;

import com.tomcat.dao.TbHongbaoBorrowDAO;
import com.tomcat.model.TbHongbaoBorrow;
import com.tomcat.model.TbHongbaoBorrowExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbHongbaoBorrowDAOImpl extends SqlMapClientDaoSupport implements TbHongbaoBorrowDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbHongbaoBorrowDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbHongbaoBorrowExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_hongbao_borrow.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbHongbaoBorrowExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_hongbao_borrow.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        TbHongbaoBorrow key = new TbHongbaoBorrow();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_hongbao_borrow.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbHongbaoBorrow record) {
        getSqlMapClientTemplate().insert("tb_hongbao_borrow.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbHongbaoBorrow record) {
        getSqlMapClientTemplate().insert("tb_hongbao_borrow.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(TbHongbaoBorrowExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_hongbao_borrow.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbHongbaoBorrow selectByPrimaryKey(Integer id) {
        TbHongbaoBorrow key = new TbHongbaoBorrow();
        key.setId(id);
        TbHongbaoBorrow record = (TbHongbaoBorrow) getSqlMapClientTemplate().queryForObject("tb_hongbao_borrow.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbHongbaoBorrow record, TbHongbaoBorrowExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_hongbao_borrow.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbHongbaoBorrow record, TbHongbaoBorrowExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_hongbao_borrow.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbHongbaoBorrow record) {
        int rows = getSqlMapClientTemplate().update("tb_hongbao_borrow.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbHongbaoBorrow record) {
        int rows = getSqlMapClientTemplate().update("tb_hongbao_borrow.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_hongbao_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbHongbaoBorrowExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbHongbaoBorrowExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}