package com.tomcat.dao.impl;

import com.tomcat.dao.TbVerifyBorrowLogDAO;
import com.tomcat.model.TbVerifyBorrowLog;
import com.tomcat.model.TbVerifyBorrowLogExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbVerifyBorrowLogDAOImpl extends SqlMapClientDaoSupport implements TbVerifyBorrowLogDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbVerifyBorrowLogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbVerifyBorrowLogExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_verify_borrow_log.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbVerifyBorrowLogExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_verify_borrow_log.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        TbVerifyBorrowLog key = new TbVerifyBorrowLog();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_verify_borrow_log.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbVerifyBorrowLog record) {
        getSqlMapClientTemplate().insert("tb_verify_borrow_log.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbVerifyBorrowLog record) {
        getSqlMapClientTemplate().insert("tb_verify_borrow_log.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(TbVerifyBorrowLogExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_verify_borrow_log.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbVerifyBorrowLog selectByPrimaryKey(Integer id) {
        TbVerifyBorrowLog key = new TbVerifyBorrowLog();
        key.setId(id);
        TbVerifyBorrowLog record = (TbVerifyBorrowLog) getSqlMapClientTemplate().queryForObject("tb_verify_borrow_log.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbVerifyBorrowLog record, TbVerifyBorrowLogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_verify_borrow_log.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbVerifyBorrowLog record, TbVerifyBorrowLogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_verify_borrow_log.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbVerifyBorrowLog record) {
        int rows = getSqlMapClientTemplate().update("tb_verify_borrow_log.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbVerifyBorrowLog record) {
        int rows = getSqlMapClientTemplate().update("tb_verify_borrow_log.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_verify_borrow_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbVerifyBorrowLogExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbVerifyBorrowLogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}