package com.tomcat.dao;

import com.tomcat.model.BorrowCollectionTransfer;
import com.tomcat.model.BorrowCollectionTransferExample;
import java.util.List;

public interface BorrowCollectionTransferDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int countByExample(BorrowCollectionTransferExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByExample(BorrowCollectionTransferExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insert(BorrowCollectionTransfer record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insertSelective(BorrowCollectionTransfer record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExample(BorrowCollectionTransferExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    BorrowCollectionTransfer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExampleSelective(BorrowCollectionTransfer record, BorrowCollectionTransferExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExample(BorrowCollectionTransfer record, BorrowCollectionTransferExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKeySelective(BorrowCollectionTransfer record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table borrow_collection_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKey(BorrowCollectionTransfer record);
}