package com.tomcat.dao;

import com.tomcat.model.TbAdminLog;
import com.tomcat.model.TbAdminLogExample;
import com.tomcat.model.TbAdminLogWithBLOBs;
import java.util.List;

public interface TbAdminLogDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int countByExample(TbAdminLogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByExample(TbAdminLogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insert(TbAdminLogWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insertSelective(TbAdminLogWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExampleWithBLOBs(TbAdminLogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExampleWithoutBLOBs(TbAdminLogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    TbAdminLogWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExampleSelective(TbAdminLogWithBLOBs record, TbAdminLogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExample(TbAdminLogWithBLOBs record, TbAdminLogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExample(TbAdminLog record, TbAdminLogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKeySelective(TbAdminLogWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKey(TbAdminLogWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_admin_log
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKey(TbAdminLog record);
}