package com.tomcat.dao;

import com.tomcat.model.TbAuthRule;
import com.tomcat.model.TbAuthRuleExample;
import com.tomcat.model.TbAuthRuleKey;
import java.util.List;

public interface TbAuthRuleDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int countByExample(TbAuthRuleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByExample(TbAuthRuleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByPrimaryKey(TbAuthRuleKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insert(TbAuthRule record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insertSelective(TbAuthRule record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExampleWithBLOBs(TbAuthRuleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExampleWithoutBLOBs(TbAuthRuleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    TbAuthRule selectByPrimaryKey(TbAuthRuleKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExampleSelective(TbAuthRule record, TbAuthRuleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExampleWithBLOBs(TbAuthRule record, TbAuthRuleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExampleWithoutBLOBs(TbAuthRule record, TbAuthRuleExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKeySelective(TbAuthRule record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(TbAuthRule record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKeyWithoutBLOBs(TbAuthRule record);
}