package com.tomcat.dao;

import com.tomcat.model.TbInterestBorrow;
import com.tomcat.model.TbInterestBorrowExample;
import java.util.List;

public interface TbInterestBorrowDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int countByExample(TbInterestBorrowExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByExample(TbInterestBorrowExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insert(TbInterestBorrow record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insertSelective(TbInterestBorrow record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExample(TbInterestBorrowExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    TbInterestBorrow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExampleSelective(TbInterestBorrow record, TbInterestBorrowExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExample(TbInterestBorrow record, TbInterestBorrowExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKeySelective(TbInterestBorrow record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKey(TbInterestBorrow record);
}