package com.tomcat.dao;

import com.tomcat.model.TbLuckydrawSetting;
import com.tomcat.model.TbLuckydrawSettingExample;
import java.util.List;

public interface TbLuckydrawSettingDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int countByExample(TbLuckydrawSettingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByExample(TbLuckydrawSettingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insert(TbLuckydrawSetting record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insertSelective(TbLuckydrawSetting record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExample(TbLuckydrawSettingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    TbLuckydrawSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExampleSelective(TbLuckydrawSetting record, TbLuckydrawSettingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExample(TbLuckydrawSetting record, TbLuckydrawSettingExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKeySelective(TbLuckydrawSetting record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_luckydraw_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKey(TbLuckydrawSetting record);
}