package com.tomcat.dao;

import com.tomcat.model.TbUserCaptcha;
import com.tomcat.model.TbUserCaptchaExample;
import java.util.List;

public interface TbUserCaptchaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int countByExample(TbUserCaptchaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByExample(TbUserCaptchaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insert(TbUserCaptcha record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insertSelective(TbUserCaptcha record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExample(TbUserCaptchaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    TbUserCaptcha selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExampleSelective(TbUserCaptcha record, TbUserCaptchaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExample(TbUserCaptcha record, TbUserCaptchaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKeySelective(TbUserCaptcha record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user_captcha
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKey(TbUserCaptcha record);
}