package com.tomcat.dao.impl;

import com.tomcat.dao.TbAuthRuleDAO;
import com.tomcat.model.TbAuthRule;
import com.tomcat.model.TbAuthRuleExample;
import com.tomcat.model.TbAuthRuleKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbAuthRuleDAOImpl extends SqlMapClientDaoSupport implements TbAuthRuleDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbAuthRuleDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbAuthRuleExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_auth_rule.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbAuthRuleExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_auth_rule.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(TbAuthRuleKey key) {
        int rows = getSqlMapClientTemplate().delete("tb_auth_rule.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbAuthRule record) {
        getSqlMapClientTemplate().insert("tb_auth_rule.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbAuthRule record) {
        getSqlMapClientTemplate().insert("tb_auth_rule.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExampleWithBLOBs(TbAuthRuleExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_auth_rule.ibatorgenerated_selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExampleWithoutBLOBs(TbAuthRuleExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_auth_rule.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbAuthRule selectByPrimaryKey(TbAuthRuleKey key) {
        TbAuthRule record = (TbAuthRule) getSqlMapClientTemplate().queryForObject("tb_auth_rule.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbAuthRule record, TbAuthRuleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_auth_rule.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleWithBLOBs(TbAuthRule record, TbAuthRuleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_auth_rule.ibatorgenerated_updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleWithoutBLOBs(TbAuthRule record, TbAuthRuleExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_auth_rule.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbAuthRule record) {
        int rows = getSqlMapClientTemplate().update("tb_auth_rule.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeyWithBLOBs(TbAuthRule record) {
        int rows = getSqlMapClientTemplate().update("tb_auth_rule.ibatorgenerated_updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeyWithoutBLOBs(TbAuthRule record) {
        int rows = getSqlMapClientTemplate().update("tb_auth_rule.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_auth_rule
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbAuthRuleExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbAuthRuleExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}