package com.tomcat.dao.impl;

import com.tomcat.dao.TbDebtTransferDAO;
import com.tomcat.model.TbDebtTransfer;
import com.tomcat.model.TbDebtTransferExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbDebtTransferDAOImpl extends SqlMapClientDaoSupport implements TbDebtTransferDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbDebtTransferDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbDebtTransferExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_debt_transfer.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbDebtTransferExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_debt_transfer.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        TbDebtTransfer key = new TbDebtTransfer();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_debt_transfer.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbDebtTransfer record) {
        getSqlMapClientTemplate().insert("tb_debt_transfer.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbDebtTransfer record) {
        getSqlMapClientTemplate().insert("tb_debt_transfer.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(TbDebtTransferExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_debt_transfer.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbDebtTransfer selectByPrimaryKey(Integer id) {
        TbDebtTransfer key = new TbDebtTransfer();
        key.setId(id);
        TbDebtTransfer record = (TbDebtTransfer) getSqlMapClientTemplate().queryForObject("tb_debt_transfer.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbDebtTransfer record, TbDebtTransferExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_debt_transfer.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbDebtTransfer record, TbDebtTransferExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_debt_transfer.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbDebtTransfer record) {
        int rows = getSqlMapClientTemplate().update("tb_debt_transfer.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbDebtTransfer record) {
        int rows = getSqlMapClientTemplate().update("tb_debt_transfer.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_debt_transfer
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbDebtTransferExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbDebtTransferExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}