package com.tomcat.dao.impl;

import com.tomcat.dao.TbInterestBorrowSettingDAO;
import com.tomcat.model.TbInterestBorrowSetting;
import com.tomcat.model.TbInterestBorrowSettingExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbInterestBorrowSettingDAOImpl extends SqlMapClientDaoSupport implements TbInterestBorrowSettingDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbInterestBorrowSettingDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbInterestBorrowSettingExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_interest_borrow_setting.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbInterestBorrowSettingExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_interest_borrow_setting.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        TbInterestBorrowSetting key = new TbInterestBorrowSetting();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_interest_borrow_setting.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbInterestBorrowSetting record) {
        getSqlMapClientTemplate().insert("tb_interest_borrow_setting.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbInterestBorrowSetting record) {
        getSqlMapClientTemplate().insert("tb_interest_borrow_setting.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(TbInterestBorrowSettingExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_interest_borrow_setting.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbInterestBorrowSetting selectByPrimaryKey(Integer id) {
        TbInterestBorrowSetting key = new TbInterestBorrowSetting();
        key.setId(id);
        TbInterestBorrowSetting record = (TbInterestBorrowSetting) getSqlMapClientTemplate().queryForObject("tb_interest_borrow_setting.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbInterestBorrowSetting record, TbInterestBorrowSettingExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_interest_borrow_setting.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbInterestBorrowSetting record, TbInterestBorrowSettingExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_interest_borrow_setting.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbInterestBorrowSetting record) {
        int rows = getSqlMapClientTemplate().update("tb_interest_borrow_setting.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbInterestBorrowSetting record) {
        int rows = getSqlMapClientTemplate().update("tb_interest_borrow_setting.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_interest_borrow_setting
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbInterestBorrowSettingExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbInterestBorrowSettingExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}