package com.tomcat.dao.impl;

import com.tomcat.dao.TbLoanOrderDAO;
import com.tomcat.model.TbLoanOrder;
import com.tomcat.model.TbLoanOrderExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbLoanOrderDAOImpl extends SqlMapClientDaoSupport implements TbLoanOrderDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbLoanOrderDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbLoanOrderExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_loan_order.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbLoanOrderExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_loan_order.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        TbLoanOrder key = new TbLoanOrder();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tb_loan_order.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbLoanOrder record) {
        getSqlMapClientTemplate().insert("tb_loan_order.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbLoanOrder record) {
        getSqlMapClientTemplate().insert("tb_loan_order.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(TbLoanOrderExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_loan_order.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbLoanOrder selectByPrimaryKey(Integer id) {
        TbLoanOrder key = new TbLoanOrder();
        key.setId(id);
        TbLoanOrder record = (TbLoanOrder) getSqlMapClientTemplate().queryForObject("tb_loan_order.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbLoanOrder record, TbLoanOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_loan_order.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbLoanOrder record, TbLoanOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_loan_order.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbLoanOrder record) {
        int rows = getSqlMapClientTemplate().update("tb_loan_order.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbLoanOrder record) {
        int rows = getSqlMapClientTemplate().update("tb_loan_order.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_loan_order
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbLoanOrderExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbLoanOrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}