package com.tomcat.dao.impl;

import com.tomcat.dao.TbLotteryNumDAO;
import com.tomcat.model.TbLotteryNum;
import com.tomcat.model.TbLotteryNumExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TbLotteryNumDAOImpl extends SqlMapClientDaoSupport implements TbLotteryNumDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbLotteryNumDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int countByExample(TbLotteryNumExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tb_lottery_num.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByExample(TbLotteryNumExample example) {
        int rows = getSqlMapClientTemplate().delete("tb_lottery_num.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int deleteByPrimaryKey(Integer userid) {
        TbLotteryNum key = new TbLotteryNum();
        key.setUserid(userid);
        int rows = getSqlMapClientTemplate().delete("tb_lottery_num.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insert(TbLotteryNum record) {
        getSqlMapClientTemplate().insert("tb_lottery_num.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void insertSelective(TbLotteryNum record) {
        getSqlMapClientTemplate().insert("tb_lottery_num.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List selectByExample(TbLotteryNumExample example) {
        List list = getSqlMapClientTemplate().queryForList("tb_lottery_num.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbLotteryNum selectByPrimaryKey(Integer userid) {
        TbLotteryNum key = new TbLotteryNum();
        key.setUserid(userid);
        TbLotteryNum record = (TbLotteryNum) getSqlMapClientTemplate().queryForObject("tb_lottery_num.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExampleSelective(TbLotteryNum record, TbLotteryNumExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_lottery_num.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByExample(TbLotteryNum record, TbLotteryNumExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tb_lottery_num.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKeySelective(TbLotteryNum record) {
        int rows = getSqlMapClientTemplate().update("tb_lottery_num.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public int updateByPrimaryKey(TbLotteryNum record) {
        int rows = getSqlMapClientTemplate().update("tb_lottery_num.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_lottery_num
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private static class UpdateByExampleParms extends TbLotteryNumExample {
        private Object record;

        public UpdateByExampleParms(Object record, TbLotteryNumExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}