package com.tomcat.model;

public class TbAdminLogWithBLOBs extends TbAdminLog {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_admin_log.prefix
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private String prefix;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_admin_log.message
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private String message;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_admin_log.prefix
     *
     * @return the value of tb_admin_log.prefix
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_admin_log.prefix
     *
     * @param prefix the value for tb_admin_log.prefix
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_admin_log.message
     *
     * @return the value of tb_admin_log.message
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_admin_log.message
     *
     * @param message the value for tb_admin_log.message
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setMessage(String message) {
        this.message = message;
    }
}