package com.tomcat.model;

public class TbArea {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_area.id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_area.area_id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private Integer areaId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_area.area
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private String area;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_area.parent_id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private Integer parentId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_area.id
     *
     * @return the value of tb_area.id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_area.id
     *
     * @param id the value for tb_area.id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_area.area_id
     *
     * @return the value of tb_area.area_id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_area.area_id
     *
     * @param areaId the value for tb_area.area_id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_area.area
     *
     * @return the value of tb_area.area
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_area.area
     *
     * @param area the value for tb_area.area
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_area.parent_id
     *
     * @return the value of tb_area.parent_id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_area.parent_id
     *
     * @param parentId the value for tb_area.parent_id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}