package com.tomcat.model;

public class TbAuthItemChild {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_auth_item_child.id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_auth_item_child.parent
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private String parent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_auth_item_child.child
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private String child;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tb_auth_item_child.description
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    private String description;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_auth_item_child.id
     *
     * @return the value of tb_auth_item_child.id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_auth_item_child.id
     *
     * @param id the value for tb_auth_item_child.id
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_auth_item_child.parent
     *
     * @return the value of tb_auth_item_child.parent
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_auth_item_child.parent
     *
     * @param parent the value for tb_auth_item_child.parent
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setParent(String parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_auth_item_child.child
     *
     * @return the value of tb_auth_item_child.child
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public String getChild() {
        return child;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_auth_item_child.child
     *
     * @param child the value for tb_auth_item_child.child
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setChild(String child) {
        this.child = child;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tb_auth_item_child.description
     *
     * @return the value of tb_auth_item_child.description
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tb_auth_item_child.description
     *
     * @param description the value for tb_auth_item_child.description
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}