package com.tomcat.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TbLotteryExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbLotteryExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected TbLotteryExample(TbLotteryExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_lottery
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("userId =", value, "userid");
            return this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("userId <>", value, "userid");
            return this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("userId >", value, "userid");
            return this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("userId >=", value, "userid");
            return this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("userId <", value, "userid");
            return this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("userId <=", value, "userid");
            return this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("userId like", value, "userid");
            return this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("userId not like", value, "userid");
            return this;
        }

        public Criteria andUseridIn(List values) {
            addCriterion("userId in", values, "userid");
            return this;
        }

        public Criteria andUseridNotIn(List values) {
            addCriterion("userId not in", values, "userid");
            return this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("userId between", value1, value2, "userid");
            return this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return this;
        }

        public Criteria andJiangpinnameIsNull() {
            addCriterion("jiangpinName is null");
            return this;
        }

        public Criteria andJiangpinnameIsNotNull() {
            addCriterion("jiangpinName is not null");
            return this;
        }

        public Criteria andJiangpinnameEqualTo(String value) {
            addCriterion("jiangpinName =", value, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameNotEqualTo(String value) {
            addCriterion("jiangpinName <>", value, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameGreaterThan(String value) {
            addCriterion("jiangpinName >", value, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameGreaterThanOrEqualTo(String value) {
            addCriterion("jiangpinName >=", value, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameLessThan(String value) {
            addCriterion("jiangpinName <", value, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameLessThanOrEqualTo(String value) {
            addCriterion("jiangpinName <=", value, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameLike(String value) {
            addCriterion("jiangpinName like", value, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameNotLike(String value) {
            addCriterion("jiangpinName not like", value, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameIn(List values) {
            addCriterion("jiangpinName in", values, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameNotIn(List values) {
            addCriterion("jiangpinName not in", values, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameBetween(String value1, String value2) {
            addCriterion("jiangpinName between", value1, value2, "jiangpinname");
            return this;
        }

        public Criteria andJiangpinnameNotBetween(String value1, String value2) {
            addCriterion("jiangpinName not between", value1, value2, "jiangpinname");
            return this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("addTime is null");
            return this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("addTime is not null");
            return this;
        }

        public Criteria andAddtimeEqualTo(String value) {
            addCriterion("addTime =", value, "addtime");
            return this;
        }

        public Criteria andAddtimeNotEqualTo(String value) {
            addCriterion("addTime <>", value, "addtime");
            return this;
        }

        public Criteria andAddtimeGreaterThan(String value) {
            addCriterion("addTime >", value, "addtime");
            return this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(String value) {
            addCriterion("addTime >=", value, "addtime");
            return this;
        }

        public Criteria andAddtimeLessThan(String value) {
            addCriterion("addTime <", value, "addtime");
            return this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(String value) {
            addCriterion("addTime <=", value, "addtime");
            return this;
        }

        public Criteria andAddtimeLike(String value) {
            addCriterion("addTime like", value, "addtime");
            return this;
        }

        public Criteria andAddtimeNotLike(String value) {
            addCriterion("addTime not like", value, "addtime");
            return this;
        }

        public Criteria andAddtimeIn(List values) {
            addCriterion("addTime in", values, "addtime");
            return this;
        }

        public Criteria andAddtimeNotIn(List values) {
            addCriterion("addTime not in", values, "addtime");
            return this;
        }

        public Criteria andAddtimeBetween(String value1, String value2) {
            addCriterion("addTime between", value1, value2, "addtime");
            return this;
        }

        public Criteria andAddtimeNotBetween(String value1, String value2) {
            addCriterion("addTime not between", value1, value2, "addtime");
            return this;
        }
    }
}