package com.tomcat.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TbBorrowCollectionExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbBorrowCollectionExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected TbBorrowCollectionExample(TbBorrowCollectionExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andColOrderIsNull() {
            addCriterion("col_order is null");
            return this;
        }

        public Criteria andColOrderIsNotNull() {
            addCriterion("col_order is not null");
            return this;
        }

        public Criteria andColOrderEqualTo(Integer value) {
            addCriterion("col_order =", value, "colOrder");
            return this;
        }

        public Criteria andColOrderNotEqualTo(Integer value) {
            addCriterion("col_order <>", value, "colOrder");
            return this;
        }

        public Criteria andColOrderGreaterThan(Integer value) {
            addCriterion("col_order >", value, "colOrder");
            return this;
        }

        public Criteria andColOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("col_order >=", value, "colOrder");
            return this;
        }

        public Criteria andColOrderLessThan(Integer value) {
            addCriterion("col_order <", value, "colOrder");
            return this;
        }

        public Criteria andColOrderLessThanOrEqualTo(Integer value) {
            addCriterion("col_order <=", value, "colOrder");
            return this;
        }

        public Criteria andColOrderIn(List values) {
            addCriterion("col_order in", values, "colOrder");
            return this;
        }

        public Criteria andColOrderNotIn(List values) {
            addCriterion("col_order not in", values, "colOrder");
            return this;
        }

        public Criteria andColOrderBetween(Integer value1, Integer value2) {
            addCriterion("col_order between", value1, value2, "colOrder");
            return this;
        }

        public Criteria andColOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("col_order not between", value1, value2, "colOrder");
            return this;
        }

        public Criteria andTenderIdIsNull() {
            addCriterion("tender_id is null");
            return this;
        }

        public Criteria andTenderIdIsNotNull() {
            addCriterion("tender_id is not null");
            return this;
        }

        public Criteria andTenderIdEqualTo(Integer value) {
            addCriterion("tender_id =", value, "tenderId");
            return this;
        }

        public Criteria andTenderIdNotEqualTo(Integer value) {
            addCriterion("tender_id <>", value, "tenderId");
            return this;
        }

        public Criteria andTenderIdGreaterThan(Integer value) {
            addCriterion("tender_id >", value, "tenderId");
            return this;
        }

        public Criteria andTenderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tender_id >=", value, "tenderId");
            return this;
        }

        public Criteria andTenderIdLessThan(Integer value) {
            addCriterion("tender_id <", value, "tenderId");
            return this;
        }

        public Criteria andTenderIdLessThanOrEqualTo(Integer value) {
            addCriterion("tender_id <=", value, "tenderId");
            return this;
        }

        public Criteria andTenderIdIn(List values) {
            addCriterion("tender_id in", values, "tenderId");
            return this;
        }

        public Criteria andTenderIdNotIn(List values) {
            addCriterion("tender_id not in", values, "tenderId");
            return this;
        }

        public Criteria andTenderIdBetween(Integer value1, Integer value2) {
            addCriterion("tender_id between", value1, value2, "tenderId");
            return this;
        }

        public Criteria andTenderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tender_id not between", value1, value2, "tenderId");
            return this;
        }

        public Criteria andRepayTimeIsNull() {
            addCriterion("repay_time is null");
            return this;
        }

        public Criteria andRepayTimeIsNotNull() {
            addCriterion("repay_time is not null");
            return this;
        }

        public Criteria andRepayTimeEqualTo(Integer value) {
            addCriterion("repay_time =", value, "repayTime");
            return this;
        }

        public Criteria andRepayTimeNotEqualTo(Integer value) {
            addCriterion("repay_time <>", value, "repayTime");
            return this;
        }

        public Criteria andRepayTimeGreaterThan(Integer value) {
            addCriterion("repay_time >", value, "repayTime");
            return this;
        }

        public Criteria andRepayTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("repay_time >=", value, "repayTime");
            return this;
        }

        public Criteria andRepayTimeLessThan(Integer value) {
            addCriterion("repay_time <", value, "repayTime");
            return this;
        }

        public Criteria andRepayTimeLessThanOrEqualTo(Integer value) {
            addCriterion("repay_time <=", value, "repayTime");
            return this;
        }

        public Criteria andRepayTimeIn(List values) {
            addCriterion("repay_time in", values, "repayTime");
            return this;
        }

        public Criteria andRepayTimeNotIn(List values) {
            addCriterion("repay_time not in", values, "repayTime");
            return this;
        }

        public Criteria andRepayTimeBetween(Integer value1, Integer value2) {
            addCriterion("repay_time between", value1, value2, "repayTime");
            return this;
        }

        public Criteria andRepayTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("repay_time not between", value1, value2, "repayTime");
            return this;
        }

        public Criteria andRepayYestimeIsNull() {
            addCriterion("repay_yestime is null");
            return this;
        }

        public Criteria andRepayYestimeIsNotNull() {
            addCriterion("repay_yestime is not null");
            return this;
        }

        public Criteria andRepayYestimeEqualTo(Integer value) {
            addCriterion("repay_yestime =", value, "repayYestime");
            return this;
        }

        public Criteria andRepayYestimeNotEqualTo(Integer value) {
            addCriterion("repay_yestime <>", value, "repayYestime");
            return this;
        }

        public Criteria andRepayYestimeGreaterThan(Integer value) {
            addCriterion("repay_yestime >", value, "repayYestime");
            return this;
        }

        public Criteria andRepayYestimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("repay_yestime >=", value, "repayYestime");
            return this;
        }

        public Criteria andRepayYestimeLessThan(Integer value) {
            addCriterion("repay_yestime <", value, "repayYestime");
            return this;
        }

        public Criteria andRepayYestimeLessThanOrEqualTo(Integer value) {
            addCriterion("repay_yestime <=", value, "repayYestime");
            return this;
        }

        public Criteria andRepayYestimeIn(List values) {
            addCriterion("repay_yestime in", values, "repayYestime");
            return this;
        }

        public Criteria andRepayYestimeNotIn(List values) {
            addCriterion("repay_yestime not in", values, "repayYestime");
            return this;
        }

        public Criteria andRepayYestimeBetween(Integer value1, Integer value2) {
            addCriterion("repay_yestime between", value1, value2, "repayYestime");
            return this;
        }

        public Criteria andRepayYestimeNotBetween(Integer value1, Integer value2) {
            addCriterion("repay_yestime not between", value1, value2, "repayYestime");
            return this;
        }

        public Criteria andRepayAccountIsNull() {
            addCriterion("repay_account is null");
            return this;
        }

        public Criteria andRepayAccountIsNotNull() {
            addCriterion("repay_account is not null");
            return this;
        }

        public Criteria andRepayAccountEqualTo(BigDecimal value) {
            addCriterion("repay_account =", value, "repayAccount");
            return this;
        }

        public Criteria andRepayAccountNotEqualTo(BigDecimal value) {
            addCriterion("repay_account <>", value, "repayAccount");
            return this;
        }

        public Criteria andRepayAccountGreaterThan(BigDecimal value) {
            addCriterion("repay_account >", value, "repayAccount");
            return this;
        }

        public Criteria andRepayAccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("repay_account >=", value, "repayAccount");
            return this;
        }

        public Criteria andRepayAccountLessThan(BigDecimal value) {
            addCriterion("repay_account <", value, "repayAccount");
            return this;
        }

        public Criteria andRepayAccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("repay_account <=", value, "repayAccount");
            return this;
        }

        public Criteria andRepayAccountIn(List values) {
            addCriterion("repay_account in", values, "repayAccount");
            return this;
        }

        public Criteria andRepayAccountNotIn(List values) {
            addCriterion("repay_account not in", values, "repayAccount");
            return this;
        }

        public Criteria andRepayAccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repay_account between", value1, value2, "repayAccount");
            return this;
        }

        public Criteria andRepayAccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repay_account not between", value1, value2, "repayAccount");
            return this;
        }

        public Criteria andRepayYesaccountIsNull() {
            addCriterion("repay_yesaccount is null");
            return this;
        }

        public Criteria andRepayYesaccountIsNotNull() {
            addCriterion("repay_yesaccount is not null");
            return this;
        }

        public Criteria andRepayYesaccountEqualTo(BigDecimal value) {
            addCriterion("repay_yesaccount =", value, "repayYesaccount");
            return this;
        }

        public Criteria andRepayYesaccountNotEqualTo(BigDecimal value) {
            addCriterion("repay_yesaccount <>", value, "repayYesaccount");
            return this;
        }

        public Criteria andRepayYesaccountGreaterThan(BigDecimal value) {
            addCriterion("repay_yesaccount >", value, "repayYesaccount");
            return this;
        }

        public Criteria andRepayYesaccountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("repay_yesaccount >=", value, "repayYesaccount");
            return this;
        }

        public Criteria andRepayYesaccountLessThan(BigDecimal value) {
            addCriterion("repay_yesaccount <", value, "repayYesaccount");
            return this;
        }

        public Criteria andRepayYesaccountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("repay_yesaccount <=", value, "repayYesaccount");
            return this;
        }

        public Criteria andRepayYesaccountIn(List values) {
            addCriterion("repay_yesaccount in", values, "repayYesaccount");
            return this;
        }

        public Criteria andRepayYesaccountNotIn(List values) {
            addCriterion("repay_yesaccount not in", values, "repayYesaccount");
            return this;
        }

        public Criteria andRepayYesaccountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repay_yesaccount between", value1, value2, "repayYesaccount");
            return this;
        }

        public Criteria andRepayYesaccountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("repay_yesaccount not between", value1, value2, "repayYesaccount");
            return this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("interest is null");
            return this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("interest is not null");
            return this;
        }

        public Criteria andInterestEqualTo(BigDecimal value) {
            addCriterion("interest =", value, "interest");
            return this;
        }

        public Criteria andInterestNotEqualTo(BigDecimal value) {
            addCriterion("interest <>", value, "interest");
            return this;
        }

        public Criteria andInterestGreaterThan(BigDecimal value) {
            addCriterion("interest >", value, "interest");
            return this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("interest >=", value, "interest");
            return this;
        }

        public Criteria andInterestLessThan(BigDecimal value) {
            addCriterion("interest <", value, "interest");
            return this;
        }

        public Criteria andInterestLessThanOrEqualTo(BigDecimal value) {
            addCriterion("interest <=", value, "interest");
            return this;
        }

        public Criteria andInterestIn(List values) {
            addCriterion("interest in", values, "interest");
            return this;
        }

        public Criteria andInterestNotIn(List values) {
            addCriterion("interest not in", values, "interest");
            return this;
        }

        public Criteria andInterestBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest between", value1, value2, "interest");
            return this;
        }

        public Criteria andInterestNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("interest not between", value1, value2, "interest");
            return this;
        }

        public Criteria andCapitalIsNull() {
            addCriterion("capital is null");
            return this;
        }

        public Criteria andCapitalIsNotNull() {
            addCriterion("capital is not null");
            return this;
        }

        public Criteria andCapitalEqualTo(BigDecimal value) {
            addCriterion("capital =", value, "capital");
            return this;
        }

        public Criteria andCapitalNotEqualTo(BigDecimal value) {
            addCriterion("capital <>", value, "capital");
            return this;
        }

        public Criteria andCapitalGreaterThan(BigDecimal value) {
            addCriterion("capital >", value, "capital");
            return this;
        }

        public Criteria andCapitalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("capital >=", value, "capital");
            return this;
        }

        public Criteria andCapitalLessThan(BigDecimal value) {
            addCriterion("capital <", value, "capital");
            return this;
        }

        public Criteria andCapitalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("capital <=", value, "capital");
            return this;
        }

        public Criteria andCapitalIn(List values) {
            addCriterion("capital in", values, "capital");
            return this;
        }

        public Criteria andCapitalNotIn(List values) {
            addCriterion("capital not in", values, "capital");
            return this;
        }

        public Criteria andCapitalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("capital between", value1, value2, "capital");
            return this;
        }

        public Criteria andCapitalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("capital not between", value1, value2, "capital");
            return this;
        }

        public Criteria andLateDaysIsNull() {
            addCriterion("late_days is null");
            return this;
        }

        public Criteria andLateDaysIsNotNull() {
            addCriterion("late_days is not null");
            return this;
        }

        public Criteria andLateDaysEqualTo(Integer value) {
            addCriterion("late_days =", value, "lateDays");
            return this;
        }

        public Criteria andLateDaysNotEqualTo(Integer value) {
            addCriterion("late_days <>", value, "lateDays");
            return this;
        }

        public Criteria andLateDaysGreaterThan(Integer value) {
            addCriterion("late_days >", value, "lateDays");
            return this;
        }

        public Criteria andLateDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("late_days >=", value, "lateDays");
            return this;
        }

        public Criteria andLateDaysLessThan(Integer value) {
            addCriterion("late_days <", value, "lateDays");
            return this;
        }

        public Criteria andLateDaysLessThanOrEqualTo(Integer value) {
            addCriterion("late_days <=", value, "lateDays");
            return this;
        }

        public Criteria andLateDaysIn(List values) {
            addCriterion("late_days in", values, "lateDays");
            return this;
        }

        public Criteria andLateDaysNotIn(List values) {
            addCriterion("late_days not in", values, "lateDays");
            return this;
        }

        public Criteria andLateDaysBetween(Integer value1, Integer value2) {
            addCriterion("late_days between", value1, value2, "lateDays");
            return this;
        }

        public Criteria andLateDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("late_days not between", value1, value2, "lateDays");
            return this;
        }

        public Criteria andLateInterestIsNull() {
            addCriterion("late_interest is null");
            return this;
        }

        public Criteria andLateInterestIsNotNull() {
            addCriterion("late_interest is not null");
            return this;
        }

        public Criteria andLateInterestEqualTo(BigDecimal value) {
            addCriterion("late_interest =", value, "lateInterest");
            return this;
        }

        public Criteria andLateInterestNotEqualTo(BigDecimal value) {
            addCriterion("late_interest <>", value, "lateInterest");
            return this;
        }

        public Criteria andLateInterestGreaterThan(BigDecimal value) {
            addCriterion("late_interest >", value, "lateInterest");
            return this;
        }

        public Criteria andLateInterestGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("late_interest >=", value, "lateInterest");
            return this;
        }

        public Criteria andLateInterestLessThan(BigDecimal value) {
            addCriterion("late_interest <", value, "lateInterest");
            return this;
        }

        public Criteria andLateInterestLessThanOrEqualTo(BigDecimal value) {
            addCriterion("late_interest <=", value, "lateInterest");
            return this;
        }

        public Criteria andLateInterestIn(List values) {
            addCriterion("late_interest in", values, "lateInterest");
            return this;
        }

        public Criteria andLateInterestNotIn(List values) {
            addCriterion("late_interest not in", values, "lateInterest");
            return this;
        }

        public Criteria andLateInterestBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("late_interest between", value1, value2, "lateInterest");
            return this;
        }

        public Criteria andLateInterestNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("late_interest not between", value1, value2, "lateInterest");
            return this;
        }

        public Criteria andAddtimeIsNull() {
            addCriterion("addtime is null");
            return this;
        }

        public Criteria andAddtimeIsNotNull() {
            addCriterion("addtime is not null");
            return this;
        }

        public Criteria andAddtimeEqualTo(Integer value) {
            addCriterion("addtime =", value, "addtime");
            return this;
        }

        public Criteria andAddtimeNotEqualTo(Integer value) {
            addCriterion("addtime <>", value, "addtime");
            return this;
        }

        public Criteria andAddtimeGreaterThan(Integer value) {
            addCriterion("addtime >", value, "addtime");
            return this;
        }

        public Criteria andAddtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("addtime >=", value, "addtime");
            return this;
        }

        public Criteria andAddtimeLessThan(Integer value) {
            addCriterion("addtime <", value, "addtime");
            return this;
        }

        public Criteria andAddtimeLessThanOrEqualTo(Integer value) {
            addCriterion("addtime <=", value, "addtime");
            return this;
        }

        public Criteria andAddtimeIn(List values) {
            addCriterion("addtime in", values, "addtime");
            return this;
        }

        public Criteria andAddtimeNotIn(List values) {
            addCriterion("addtime not in", values, "addtime");
            return this;
        }

        public Criteria andAddtimeBetween(Integer value1, Integer value2) {
            addCriterion("addtime between", value1, value2, "addtime");
            return this;
        }

        public Criteria andAddtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("addtime not between", value1, value2, "addtime");
            return this;
        }

        public Criteria andAddipIsNull() {
            addCriterion("addip is null");
            return this;
        }

        public Criteria andAddipIsNotNull() {
            addCriterion("addip is not null");
            return this;
        }

        public Criteria andAddipEqualTo(String value) {
            addCriterion("addip =", value, "addip");
            return this;
        }

        public Criteria andAddipNotEqualTo(String value) {
            addCriterion("addip <>", value, "addip");
            return this;
        }

        public Criteria andAddipGreaterThan(String value) {
            addCriterion("addip >", value, "addip");
            return this;
        }

        public Criteria andAddipGreaterThanOrEqualTo(String value) {
            addCriterion("addip >=", value, "addip");
            return this;
        }

        public Criteria andAddipLessThan(String value) {
            addCriterion("addip <", value, "addip");
            return this;
        }

        public Criteria andAddipLessThanOrEqualTo(String value) {
            addCriterion("addip <=", value, "addip");
            return this;
        }

        public Criteria andAddipLike(String value) {
            addCriterion("addip like", value, "addip");
            return this;
        }

        public Criteria andAddipNotLike(String value) {
            addCriterion("addip not like", value, "addip");
            return this;
        }

        public Criteria andAddipIn(List values) {
            addCriterion("addip in", values, "addip");
            return this;
        }

        public Criteria andAddipNotIn(List values) {
            addCriterion("addip not in", values, "addip");
            return this;
        }

        public Criteria andAddipBetween(String value1, String value2) {
            addCriterion("addip between", value1, value2, "addip");
            return this;
        }

        public Criteria andAddipNotBetween(String value1, String value2) {
            addCriterion("addip not between", value1, value2, "addip");
            return this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return this;
        }

        public Criteria andUpdatetimeEqualTo(Integer value) {
            addCriterion("updatetime =", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeNotEqualTo(Integer value) {
            addCriterion("updatetime <>", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeGreaterThan(Integer value) {
            addCriterion("updatetime >", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("updatetime >=", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeLessThan(Integer value) {
            addCriterion("updatetime <", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Integer value) {
            addCriterion("updatetime <=", value, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeIn(List values) {
            addCriterion("updatetime in", values, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeNotIn(List values) {
            addCriterion("updatetime not in", values, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeBetween(Integer value1, Integer value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return this;
        }

        public Criteria andUpdatetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return this;
        }

        public Criteria andUpdateipIsNull() {
            addCriterion("updateip is null");
            return this;
        }

        public Criteria andUpdateipIsNotNull() {
            addCriterion("updateip is not null");
            return this;
        }

        public Criteria andUpdateipEqualTo(String value) {
            addCriterion("updateip =", value, "updateip");
            return this;
        }

        public Criteria andUpdateipNotEqualTo(String value) {
            addCriterion("updateip <>", value, "updateip");
            return this;
        }

        public Criteria andUpdateipGreaterThan(String value) {
            addCriterion("updateip >", value, "updateip");
            return this;
        }

        public Criteria andUpdateipGreaterThanOrEqualTo(String value) {
            addCriterion("updateip >=", value, "updateip");
            return this;
        }

        public Criteria andUpdateipLessThan(String value) {
            addCriterion("updateip <", value, "updateip");
            return this;
        }

        public Criteria andUpdateipLessThanOrEqualTo(String value) {
            addCriterion("updateip <=", value, "updateip");
            return this;
        }

        public Criteria andUpdateipLike(String value) {
            addCriterion("updateip like", value, "updateip");
            return this;
        }

        public Criteria andUpdateipNotLike(String value) {
            addCriterion("updateip not like", value, "updateip");
            return this;
        }

        public Criteria andUpdateipIn(List values) {
            addCriterion("updateip in", values, "updateip");
            return this;
        }

        public Criteria andUpdateipNotIn(List values) {
            addCriterion("updateip not in", values, "updateip");
            return this;
        }

        public Criteria andUpdateipBetween(String value1, String value2) {
            addCriterion("updateip between", value1, value2, "updateip");
            return this;
        }

        public Criteria andUpdateipNotBetween(String value1, String value2) {
            addCriterion("updateip not between", value1, value2, "updateip");
            return this;
        }

        public Criteria andIsTransferIsNull() {
            addCriterion("is_transfer is null");
            return this;
        }

        public Criteria andIsTransferIsNotNull() {
            addCriterion("is_transfer is not null");
            return this;
        }

        public Criteria andIsTransferEqualTo(Integer value) {
            addCriterion("is_transfer =", value, "isTransfer");
            return this;
        }

        public Criteria andIsTransferNotEqualTo(Integer value) {
            addCriterion("is_transfer <>", value, "isTransfer");
            return this;
        }

        public Criteria andIsTransferGreaterThan(Integer value) {
            addCriterion("is_transfer >", value, "isTransfer");
            return this;
        }

        public Criteria andIsTransferGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_transfer >=", value, "isTransfer");
            return this;
        }

        public Criteria andIsTransferLessThan(Integer value) {
            addCriterion("is_transfer <", value, "isTransfer");
            return this;
        }

        public Criteria andIsTransferLessThanOrEqualTo(Integer value) {
            addCriterion("is_transfer <=", value, "isTransfer");
            return this;
        }

        public Criteria andIsTransferIn(List values) {
            addCriterion("is_transfer in", values, "isTransfer");
            return this;
        }

        public Criteria andIsTransferNotIn(List values) {
            addCriterion("is_transfer not in", values, "isTransfer");
            return this;
        }

        public Criteria andIsTransferBetween(Integer value1, Integer value2) {
            addCriterion("is_transfer between", value1, value2, "isTransfer");
            return this;
        }

        public Criteria andIsTransferNotBetween(Integer value1, Integer value2) {
            addCriterion("is_transfer not between", value1, value2, "isTransfer");
            return this;
        }
    }
}