package com.tomcat.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TbUserExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public TbUserExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected TbUserExample(TbUserExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tb_user
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andRoleIsNull() {
            addCriterion("role is null");
            return this;
        }

        public Criteria andRoleIsNotNull() {
            addCriterion("role is not null");
            return this;
        }

        public Criteria andRoleEqualTo(Byte value) {
            addCriterion("role =", value, "role");
            return this;
        }

        public Criteria andRoleNotEqualTo(Byte value) {
            addCriterion("role <>", value, "role");
            return this;
        }

        public Criteria andRoleGreaterThan(Byte value) {
            addCriterion("role >", value, "role");
            return this;
        }

        public Criteria andRoleGreaterThanOrEqualTo(Byte value) {
            addCriterion("role >=", value, "role");
            return this;
        }

        public Criteria andRoleLessThan(Byte value) {
            addCriterion("role <", value, "role");
            return this;
        }

        public Criteria andRoleLessThanOrEqualTo(Byte value) {
            addCriterion("role <=", value, "role");
            return this;
        }

        public Criteria andRoleIn(List values) {
            addCriterion("role in", values, "role");
            return this;
        }

        public Criteria andRoleNotIn(List values) {
            addCriterion("role not in", values, "role");
            return this;
        }

        public Criteria andRoleBetween(Byte value1, Byte value2) {
            addCriterion("role between", value1, value2, "role");
            return this;
        }

        public Criteria andRoleNotBetween(Byte value1, Byte value2) {
            addCriterion("role not between", value1, value2, "role");
            return this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("user_type is null");
            return this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("user_type is not null");
            return this;
        }

        public Criteria andUserTypeEqualTo(Byte value) {
            addCriterion("user_type =", value, "userType");
            return this;
        }

        public Criteria andUserTypeNotEqualTo(Byte value) {
            addCriterion("user_type <>", value, "userType");
            return this;
        }

        public Criteria andUserTypeGreaterThan(Byte value) {
            addCriterion("user_type >", value, "userType");
            return this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("user_type >=", value, "userType");
            return this;
        }

        public Criteria andUserTypeLessThan(Byte value) {
            addCriterion("user_type <", value, "userType");
            return this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(Byte value) {
            addCriterion("user_type <=", value, "userType");
            return this;
        }

        public Criteria andUserTypeIn(List values) {
            addCriterion("user_type in", values, "userType");
            return this;
        }

        public Criteria andUserTypeNotIn(List values) {
            addCriterion("user_type not in", values, "userType");
            return this;
        }

        public Criteria andUserTypeBetween(Byte value1, Byte value2) {
            addCriterion("user_type between", value1, value2, "userType");
            return this;
        }

        public Criteria andUserTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("user_type not between", value1, value2, "userType");
            return this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return this;
        }

        public Criteria andUsernameIn(List values) {
            addCriterion("username in", values, "username");
            return this;
        }

        public Criteria andUsernameNotIn(List values) {
            addCriterion("username not in", values, "username");
            return this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return this;
        }

        public Criteria andUserNoIsNull() {
            addCriterion("user_no is null");
            return this;
        }

        public Criteria andUserNoIsNotNull() {
            addCriterion("user_no is not null");
            return this;
        }

        public Criteria andUserNoEqualTo(String value) {
            addCriterion("user_no =", value, "userNo");
            return this;
        }

        public Criteria andUserNoNotEqualTo(String value) {
            addCriterion("user_no <>", value, "userNo");
            return this;
        }

        public Criteria andUserNoGreaterThan(String value) {
            addCriterion("user_no >", value, "userNo");
            return this;
        }

        public Criteria andUserNoGreaterThanOrEqualTo(String value) {
            addCriterion("user_no >=", value, "userNo");
            return this;
        }

        public Criteria andUserNoLessThan(String value) {
            addCriterion("user_no <", value, "userNo");
            return this;
        }

        public Criteria andUserNoLessThanOrEqualTo(String value) {
            addCriterion("user_no <=", value, "userNo");
            return this;
        }

        public Criteria andUserNoLike(String value) {
            addCriterion("user_no like", value, "userNo");
            return this;
        }

        public Criteria andUserNoNotLike(String value) {
            addCriterion("user_no not like", value, "userNo");
            return this;
        }

        public Criteria andUserNoIn(List values) {
            addCriterion("user_no in", values, "userNo");
            return this;
        }

        public Criteria andUserNoNotIn(List values) {
            addCriterion("user_no not in", values, "userNo");
            return this;
        }

        public Criteria andUserNoBetween(String value1, String value2) {
            addCriterion("user_no between", value1, value2, "userNo");
            return this;
        }

        public Criteria andUserNoNotBetween(String value1, String value2) {
            addCriterion("user_no not between", value1, value2, "userNo");
            return this;
        }

        public Criteria andPasswordHashIsNull() {
            addCriterion("password_hash is null");
            return this;
        }

        public Criteria andPasswordHashIsNotNull() {
            addCriterion("password_hash is not null");
            return this;
        }

        public Criteria andPasswordHashEqualTo(String value) {
            addCriterion("password_hash =", value, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashNotEqualTo(String value) {
            addCriterion("password_hash <>", value, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashGreaterThan(String value) {
            addCriterion("password_hash >", value, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashGreaterThanOrEqualTo(String value) {
            addCriterion("password_hash >=", value, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashLessThan(String value) {
            addCriterion("password_hash <", value, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashLessThanOrEqualTo(String value) {
            addCriterion("password_hash <=", value, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashLike(String value) {
            addCriterion("password_hash like", value, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashNotLike(String value) {
            addCriterion("password_hash not like", value, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashIn(List values) {
            addCriterion("password_hash in", values, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashNotIn(List values) {
            addCriterion("password_hash not in", values, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashBetween(String value1, String value2) {
            addCriterion("password_hash between", value1, value2, "passwordHash");
            return this;
        }

        public Criteria andPasswordHashNotBetween(String value1, String value2) {
            addCriterion("password_hash not between", value1, value2, "passwordHash");
            return this;
        }

        public Criteria andPasswordPayHashIsNull() {
            addCriterion("password_pay_hash is null");
            return this;
        }

        public Criteria andPasswordPayHashIsNotNull() {
            addCriterion("password_pay_hash is not null");
            return this;
        }

        public Criteria andPasswordPayHashEqualTo(String value) {
            addCriterion("password_pay_hash =", value, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashNotEqualTo(String value) {
            addCriterion("password_pay_hash <>", value, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashGreaterThan(String value) {
            addCriterion("password_pay_hash >", value, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashGreaterThanOrEqualTo(String value) {
            addCriterion("password_pay_hash >=", value, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashLessThan(String value) {
            addCriterion("password_pay_hash <", value, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashLessThanOrEqualTo(String value) {
            addCriterion("password_pay_hash <=", value, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashLike(String value) {
            addCriterion("password_pay_hash like", value, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashNotLike(String value) {
            addCriterion("password_pay_hash not like", value, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashIn(List values) {
            addCriterion("password_pay_hash in", values, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashNotIn(List values) {
            addCriterion("password_pay_hash not in", values, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashBetween(String value1, String value2) {
            addCriterion("password_pay_hash between", value1, value2, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordPayHashNotBetween(String value1, String value2) {
            addCriterion("password_pay_hash not between", value1, value2, "passwordPayHash");
            return this;
        }

        public Criteria andPasswordResetTokenIsNull() {
            addCriterion("password_reset_token is null");
            return this;
        }

        public Criteria andPasswordResetTokenIsNotNull() {
            addCriterion("password_reset_token is not null");
            return this;
        }

        public Criteria andPasswordResetTokenEqualTo(String value) {
            addCriterion("password_reset_token =", value, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenNotEqualTo(String value) {
            addCriterion("password_reset_token <>", value, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenGreaterThan(String value) {
            addCriterion("password_reset_token >", value, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenGreaterThanOrEqualTo(String value) {
            addCriterion("password_reset_token >=", value, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenLessThan(String value) {
            addCriterion("password_reset_token <", value, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenLessThanOrEqualTo(String value) {
            addCriterion("password_reset_token <=", value, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenLike(String value) {
            addCriterion("password_reset_token like", value, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenNotLike(String value) {
            addCriterion("password_reset_token not like", value, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenIn(List values) {
            addCriterion("password_reset_token in", values, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenNotIn(List values) {
            addCriterion("password_reset_token not in", values, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenBetween(String value1, String value2) {
            addCriterion("password_reset_token between", value1, value2, "passwordResetToken");
            return this;
        }

        public Criteria andPasswordResetTokenNotBetween(String value1, String value2) {
            addCriterion("password_reset_token not between", value1, value2, "passwordResetToken");
            return this;
        }

        public Criteria andAuthKeyIsNull() {
            addCriterion("auth_key is null");
            return this;
        }

        public Criteria andAuthKeyIsNotNull() {
            addCriterion("auth_key is not null");
            return this;
        }

        public Criteria andAuthKeyEqualTo(String value) {
            addCriterion("auth_key =", value, "authKey");
            return this;
        }

        public Criteria andAuthKeyNotEqualTo(String value) {
            addCriterion("auth_key <>", value, "authKey");
            return this;
        }

        public Criteria andAuthKeyGreaterThan(String value) {
            addCriterion("auth_key >", value, "authKey");
            return this;
        }

        public Criteria andAuthKeyGreaterThanOrEqualTo(String value) {
            addCriterion("auth_key >=", value, "authKey");
            return this;
        }

        public Criteria andAuthKeyLessThan(String value) {
            addCriterion("auth_key <", value, "authKey");
            return this;
        }

        public Criteria andAuthKeyLessThanOrEqualTo(String value) {
            addCriterion("auth_key <=", value, "authKey");
            return this;
        }

        public Criteria andAuthKeyLike(String value) {
            addCriterion("auth_key like", value, "authKey");
            return this;
        }

        public Criteria andAuthKeyNotLike(String value) {
            addCriterion("auth_key not like", value, "authKey");
            return this;
        }

        public Criteria andAuthKeyIn(List values) {
            addCriterion("auth_key in", values, "authKey");
            return this;
        }

        public Criteria andAuthKeyNotIn(List values) {
            addCriterion("auth_key not in", values, "authKey");
            return this;
        }

        public Criteria andAuthKeyBetween(String value1, String value2) {
            addCriterion("auth_key between", value1, value2, "authKey");
            return this;
        }

        public Criteria andAuthKeyNotBetween(String value1, String value2) {
            addCriterion("auth_key not between", value1, value2, "authKey");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusIn(List values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return this;
        }

        public Criteria andMobileIn(List values) {
            addCriterion("mobile in", values, "mobile");
            return this;
        }

        public Criteria andMobileNotIn(List values) {
            addCriterion("mobile not in", values, "mobile");
            return this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List values) {
            addCriterion("email in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List values) {
            addCriterion("email not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return this;
        }

        public Criteria andRealnameIsNull() {
            addCriterion("realname is null");
            return this;
        }

        public Criteria andRealnameIsNotNull() {
            addCriterion("realname is not null");
            return this;
        }

        public Criteria andRealnameEqualTo(String value) {
            addCriterion("realname =", value, "realname");
            return this;
        }

        public Criteria andRealnameNotEqualTo(String value) {
            addCriterion("realname <>", value, "realname");
            return this;
        }

        public Criteria andRealnameGreaterThan(String value) {
            addCriterion("realname >", value, "realname");
            return this;
        }

        public Criteria andRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("realname >=", value, "realname");
            return this;
        }

        public Criteria andRealnameLessThan(String value) {
            addCriterion("realname <", value, "realname");
            return this;
        }

        public Criteria andRealnameLessThanOrEqualTo(String value) {
            addCriterion("realname <=", value, "realname");
            return this;
        }

        public Criteria andRealnameLike(String value) {
            addCriterion("realname like", value, "realname");
            return this;
        }

        public Criteria andRealnameNotLike(String value) {
            addCriterion("realname not like", value, "realname");
            return this;
        }

        public Criteria andRealnameIn(List values) {
            addCriterion("realname in", values, "realname");
            return this;
        }

        public Criteria andRealnameNotIn(List values) {
            addCriterion("realname not in", values, "realname");
            return this;
        }

        public Criteria andRealnameBetween(String value1, String value2) {
            addCriterion("realname between", value1, value2, "realname");
            return this;
        }

        public Criteria andRealnameNotBetween(String value1, String value2) {
            addCriterion("realname not between", value1, value2, "realname");
            return this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return this;
        }

        public Criteria andIdCardIn(List values) {
            addCriterion("id_card in", values, "idCard");
            return this;
        }

        public Criteria andIdCardNotIn(List values) {
            addCriterion("id_card not in", values, "idCard");
            return this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return this;
        }

        public Criteria andSexEqualTo(Byte value) {
            addCriterion("sex =", value, "sex");
            return this;
        }

        public Criteria andSexNotEqualTo(Byte value) {
            addCriterion("sex <>", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThan(Byte value) {
            addCriterion("sex >", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Byte value) {
            addCriterion("sex >=", value, "sex");
            return this;
        }

        public Criteria andSexLessThan(Byte value) {
            addCriterion("sex <", value, "sex");
            return this;
        }

        public Criteria andSexLessThanOrEqualTo(Byte value) {
            addCriterion("sex <=", value, "sex");
            return this;
        }

        public Criteria andSexIn(List values) {
            addCriterion("sex in", values, "sex");
            return this;
        }

        public Criteria andSexNotIn(List values) {
            addCriterion("sex not in", values, "sex");
            return this;
        }

        public Criteria andSexBetween(Byte value1, Byte value2) {
            addCriterion("sex between", value1, value2, "sex");
            return this;
        }

        public Criteria andSexNotBetween(Byte value1, Byte value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return this;
        }

        public Criteria andLitpicIsNull() {
            addCriterion("litpic is null");
            return this;
        }

        public Criteria andLitpicIsNotNull() {
            addCriterion("litpic is not null");
            return this;
        }

        public Criteria andLitpicEqualTo(String value) {
            addCriterion("litpic =", value, "litpic");
            return this;
        }

        public Criteria andLitpicNotEqualTo(String value) {
            addCriterion("litpic <>", value, "litpic");
            return this;
        }

        public Criteria andLitpicGreaterThan(String value) {
            addCriterion("litpic >", value, "litpic");
            return this;
        }

        public Criteria andLitpicGreaterThanOrEqualTo(String value) {
            addCriterion("litpic >=", value, "litpic");
            return this;
        }

        public Criteria andLitpicLessThan(String value) {
            addCriterion("litpic <", value, "litpic");
            return this;
        }

        public Criteria andLitpicLessThanOrEqualTo(String value) {
            addCriterion("litpic <=", value, "litpic");
            return this;
        }

        public Criteria andLitpicLike(String value) {
            addCriterion("litpic like", value, "litpic");
            return this;
        }

        public Criteria andLitpicNotLike(String value) {
            addCriterion("litpic not like", value, "litpic");
            return this;
        }

        public Criteria andLitpicIn(List values) {
            addCriterion("litpic in", values, "litpic");
            return this;
        }

        public Criteria andLitpicNotIn(List values) {
            addCriterion("litpic not in", values, "litpic");
            return this;
        }

        public Criteria andLitpicBetween(String value1, String value2) {
            addCriterion("litpic between", value1, value2, "litpic");
            return this;
        }

        public Criteria andLitpicNotBetween(String value1, String value2) {
            addCriterion("litpic not between", value1, value2, "litpic");
            return this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return this;
        }

        public Criteria andBirthdayEqualTo(String value) {
            addCriterion("birthday =", value, "birthday");
            return this;
        }

        public Criteria andBirthdayNotEqualTo(String value) {
            addCriterion("birthday <>", value, "birthday");
            return this;
        }

        public Criteria andBirthdayGreaterThan(String value) {
            addCriterion("birthday >", value, "birthday");
            return this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("birthday >=", value, "birthday");
            return this;
        }

        public Criteria andBirthdayLessThan(String value) {
            addCriterion("birthday <", value, "birthday");
            return this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(String value) {
            addCriterion("birthday <=", value, "birthday");
            return this;
        }

        public Criteria andBirthdayLike(String value) {
            addCriterion("birthday like", value, "birthday");
            return this;
        }

        public Criteria andBirthdayNotLike(String value) {
            addCriterion("birthday not like", value, "birthday");
            return this;
        }

        public Criteria andBirthdayIn(List values) {
            addCriterion("birthday in", values, "birthday");
            return this;
        }

        public Criteria andBirthdayNotIn(List values) {
            addCriterion("birthday not in", values, "birthday");
            return this;
        }

        public Criteria andBirthdayBetween(String value1, String value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return this;
        }

        public Criteria andBirthdayNotBetween(String value1, String value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return this;
        }

        public Criteria andEmailBindingStatusIsNull() {
            addCriterion("email_binding_status is null");
            return this;
        }

        public Criteria andEmailBindingStatusIsNotNull() {
            addCriterion("email_binding_status is not null");
            return this;
        }

        public Criteria andEmailBindingStatusEqualTo(Byte value) {
            addCriterion("email_binding_status =", value, "emailBindingStatus");
            return this;
        }

        public Criteria andEmailBindingStatusNotEqualTo(Byte value) {
            addCriterion("email_binding_status <>", value, "emailBindingStatus");
            return this;
        }

        public Criteria andEmailBindingStatusGreaterThan(Byte value) {
            addCriterion("email_binding_status >", value, "emailBindingStatus");
            return this;
        }

        public Criteria andEmailBindingStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("email_binding_status >=", value, "emailBindingStatus");
            return this;
        }

        public Criteria andEmailBindingStatusLessThan(Byte value) {
            addCriterion("email_binding_status <", value, "emailBindingStatus");
            return this;
        }

        public Criteria andEmailBindingStatusLessThanOrEqualTo(Byte value) {
            addCriterion("email_binding_status <=", value, "emailBindingStatus");
            return this;
        }

        public Criteria andEmailBindingStatusIn(List values) {
            addCriterion("email_binding_status in", values, "emailBindingStatus");
            return this;
        }

        public Criteria andEmailBindingStatusNotIn(List values) {
            addCriterion("email_binding_status not in", values, "emailBindingStatus");
            return this;
        }

        public Criteria andEmailBindingStatusBetween(Byte value1, Byte value2) {
            addCriterion("email_binding_status between", value1, value2, "emailBindingStatus");
            return this;
        }

        public Criteria andEmailBindingStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("email_binding_status not between", value1, value2, "emailBindingStatus");
            return this;
        }

        public Criteria andMobileBindingStatusIsNull() {
            addCriterion("mobile_binding_status is null");
            return this;
        }

        public Criteria andMobileBindingStatusIsNotNull() {
            addCriterion("mobile_binding_status is not null");
            return this;
        }

        public Criteria andMobileBindingStatusEqualTo(Byte value) {
            addCriterion("mobile_binding_status =", value, "mobileBindingStatus");
            return this;
        }

        public Criteria andMobileBindingStatusNotEqualTo(Byte value) {
            addCriterion("mobile_binding_status <>", value, "mobileBindingStatus");
            return this;
        }

        public Criteria andMobileBindingStatusGreaterThan(Byte value) {
            addCriterion("mobile_binding_status >", value, "mobileBindingStatus");
            return this;
        }

        public Criteria andMobileBindingStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("mobile_binding_status >=", value, "mobileBindingStatus");
            return this;
        }

        public Criteria andMobileBindingStatusLessThan(Byte value) {
            addCriterion("mobile_binding_status <", value, "mobileBindingStatus");
            return this;
        }

        public Criteria andMobileBindingStatusLessThanOrEqualTo(Byte value) {
            addCriterion("mobile_binding_status <=", value, "mobileBindingStatus");
            return this;
        }

        public Criteria andMobileBindingStatusIn(List values) {
            addCriterion("mobile_binding_status in", values, "mobileBindingStatus");
            return this;
        }

        public Criteria andMobileBindingStatusNotIn(List values) {
            addCriterion("mobile_binding_status not in", values, "mobileBindingStatus");
            return this;
        }

        public Criteria andMobileBindingStatusBetween(Byte value1, Byte value2) {
            addCriterion("mobile_binding_status between", value1, value2, "mobileBindingStatus");
            return this;
        }

        public Criteria andMobileBindingStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("mobile_binding_status not between", value1, value2, "mobileBindingStatus");
            return this;
        }

        public Criteria andRealVerifyStatusIsNull() {
            addCriterion("real_verify_status is null");
            return this;
        }

        public Criteria andRealVerifyStatusIsNotNull() {
            addCriterion("real_verify_status is not null");
            return this;
        }

        public Criteria andRealVerifyStatusEqualTo(Byte value) {
            addCriterion("real_verify_status =", value, "realVerifyStatus");
            return this;
        }

        public Criteria andRealVerifyStatusNotEqualTo(Byte value) {
            addCriterion("real_verify_status <>", value, "realVerifyStatus");
            return this;
        }

        public Criteria andRealVerifyStatusGreaterThan(Byte value) {
            addCriterion("real_verify_status >", value, "realVerifyStatus");
            return this;
        }

        public Criteria andRealVerifyStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("real_verify_status >=", value, "realVerifyStatus");
            return this;
        }

        public Criteria andRealVerifyStatusLessThan(Byte value) {
            addCriterion("real_verify_status <", value, "realVerifyStatus");
            return this;
        }

        public Criteria andRealVerifyStatusLessThanOrEqualTo(Byte value) {
            addCriterion("real_verify_status <=", value, "realVerifyStatus");
            return this;
        }

        public Criteria andRealVerifyStatusIn(List values) {
            addCriterion("real_verify_status in", values, "realVerifyStatus");
            return this;
        }

        public Criteria andRealVerifyStatusNotIn(List values) {
            addCriterion("real_verify_status not in", values, "realVerifyStatus");
            return this;
        }

        public Criteria andRealVerifyStatusBetween(Byte value1, Byte value2) {
            addCriterion("real_verify_status between", value1, value2, "realVerifyStatus");
            return this;
        }

        public Criteria andRealVerifyStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("real_verify_status not between", value1, value2, "realVerifyStatus");
            return this;
        }

        public Criteria andCardBindingStatusIsNull() {
            addCriterion("card_binding_status is null");
            return this;
        }

        public Criteria andCardBindingStatusIsNotNull() {
            addCriterion("card_binding_status is not null");
            return this;
        }

        public Criteria andCardBindingStatusEqualTo(Byte value) {
            addCriterion("card_binding_status =", value, "cardBindingStatus");
            return this;
        }

        public Criteria andCardBindingStatusNotEqualTo(Byte value) {
            addCriterion("card_binding_status <>", value, "cardBindingStatus");
            return this;
        }

        public Criteria andCardBindingStatusGreaterThan(Byte value) {
            addCriterion("card_binding_status >", value, "cardBindingStatus");
            return this;
        }

        public Criteria andCardBindingStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("card_binding_status >=", value, "cardBindingStatus");
            return this;
        }

        public Criteria andCardBindingStatusLessThan(Byte value) {
            addCriterion("card_binding_status <", value, "cardBindingStatus");
            return this;
        }

        public Criteria andCardBindingStatusLessThanOrEqualTo(Byte value) {
            addCriterion("card_binding_status <=", value, "cardBindingStatus");
            return this;
        }

        public Criteria andCardBindingStatusIn(List values) {
            addCriterion("card_binding_status in", values, "cardBindingStatus");
            return this;
        }

        public Criteria andCardBindingStatusNotIn(List values) {
            addCriterion("card_binding_status not in", values, "cardBindingStatus");
            return this;
        }

        public Criteria andCardBindingStatusBetween(Byte value1, Byte value2) {
            addCriterion("card_binding_status between", value1, value2, "cardBindingStatus");
            return this;
        }

        public Criteria andCardBindingStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("card_binding_status not between", value1, value2, "cardBindingStatus");
            return this;
        }

        public Criteria andSinaOpenStatusIsNull() {
            addCriterion("sina_open_status is null");
            return this;
        }

        public Criteria andSinaOpenStatusIsNotNull() {
            addCriterion("sina_open_status is not null");
            return this;
        }

        public Criteria andSinaOpenStatusEqualTo(Integer value) {
            addCriterion("sina_open_status =", value, "sinaOpenStatus");
            return this;
        }

        public Criteria andSinaOpenStatusNotEqualTo(Integer value) {
            addCriterion("sina_open_status <>", value, "sinaOpenStatus");
            return this;
        }

        public Criteria andSinaOpenStatusGreaterThan(Integer value) {
            addCriterion("sina_open_status >", value, "sinaOpenStatus");
            return this;
        }

        public Criteria andSinaOpenStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sina_open_status >=", value, "sinaOpenStatus");
            return this;
        }

        public Criteria andSinaOpenStatusLessThan(Integer value) {
            addCriterion("sina_open_status <", value, "sinaOpenStatus");
            return this;
        }

        public Criteria andSinaOpenStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sina_open_status <=", value, "sinaOpenStatus");
            return this;
        }

        public Criteria andSinaOpenStatusIn(List values) {
            addCriterion("sina_open_status in", values, "sinaOpenStatus");
            return this;
        }

        public Criteria andSinaOpenStatusNotIn(List values) {
            addCriterion("sina_open_status not in", values, "sinaOpenStatus");
            return this;
        }

        public Criteria andSinaOpenStatusBetween(Integer value1, Integer value2) {
            addCriterion("sina_open_status between", value1, value2, "sinaOpenStatus");
            return this;
        }

        public Criteria andSinaOpenStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sina_open_status not between", value1, value2, "sinaOpenStatus");
            return this;
        }

        public Criteria andCardIdBaseIsNull() {
            addCriterion("card_id_base is null");
            return this;
        }

        public Criteria andCardIdBaseIsNotNull() {
            addCriterion("card_id_base is not null");
            return this;
        }

        public Criteria andCardIdBaseEqualTo(Integer value) {
            addCriterion("card_id_base =", value, "cardIdBase");
            return this;
        }

        public Criteria andCardIdBaseNotEqualTo(Integer value) {
            addCriterion("card_id_base <>", value, "cardIdBase");
            return this;
        }

        public Criteria andCardIdBaseGreaterThan(Integer value) {
            addCriterion("card_id_base >", value, "cardIdBase");
            return this;
        }

        public Criteria andCardIdBaseGreaterThanOrEqualTo(Integer value) {
            addCriterion("card_id_base >=", value, "cardIdBase");
            return this;
        }

        public Criteria andCardIdBaseLessThan(Integer value) {
            addCriterion("card_id_base <", value, "cardIdBase");
            return this;
        }

        public Criteria andCardIdBaseLessThanOrEqualTo(Integer value) {
            addCriterion("card_id_base <=", value, "cardIdBase");
            return this;
        }

        public Criteria andCardIdBaseIn(List values) {
            addCriterion("card_id_base in", values, "cardIdBase");
            return this;
        }

        public Criteria andCardIdBaseNotIn(List values) {
            addCriterion("card_id_base not in", values, "cardIdBase");
            return this;
        }

        public Criteria andCardIdBaseBetween(Integer value1, Integer value2) {
            addCriterion("card_id_base between", value1, value2, "cardIdBase");
            return this;
        }

        public Criteria andCardIdBaseNotBetween(Integer value1, Integer value2) {
            addCriterion("card_id_base not between", value1, value2, "cardIdBase");
            return this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return this;
        }

        public Criteria andCreatedAtEqualTo(Integer value) {
            addCriterion("created_at =", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtNotEqualTo(Integer value) {
            addCriterion("created_at <>", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtGreaterThan(Integer value) {
            addCriterion("created_at >", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Integer value) {
            addCriterion("created_at >=", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtLessThan(Integer value) {
            addCriterion("created_at <", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Integer value) {
            addCriterion("created_at <=", value, "createdAt");
            return this;
        }

        public Criteria andCreatedAtIn(List values) {
            addCriterion("created_at in", values, "createdAt");
            return this;
        }

        public Criteria andCreatedAtNotIn(List values) {
            addCriterion("created_at not in", values, "createdAt");
            return this;
        }

        public Criteria andCreatedAtBetween(Integer value1, Integer value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return this;
        }

        public Criteria andCreatedAtNotBetween(Integer value1, Integer value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return this;
        }

        public Criteria andLastLogintimeIsNull() {
            addCriterion("last_logintime is null");
            return this;
        }

        public Criteria andLastLogintimeIsNotNull() {
            addCriterion("last_logintime is not null");
            return this;
        }

        public Criteria andLastLogintimeEqualTo(Integer value) {
            addCriterion("last_logintime =", value, "lastLogintime");
            return this;
        }

        public Criteria andLastLogintimeNotEqualTo(Integer value) {
            addCriterion("last_logintime <>", value, "lastLogintime");
            return this;
        }

        public Criteria andLastLogintimeGreaterThan(Integer value) {
            addCriterion("last_logintime >", value, "lastLogintime");
            return this;
        }

        public Criteria andLastLogintimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("last_logintime >=", value, "lastLogintime");
            return this;
        }

        public Criteria andLastLogintimeLessThan(Integer value) {
            addCriterion("last_logintime <", value, "lastLogintime");
            return this;
        }

        public Criteria andLastLogintimeLessThanOrEqualTo(Integer value) {
            addCriterion("last_logintime <=", value, "lastLogintime");
            return this;
        }

        public Criteria andLastLogintimeIn(List values) {
            addCriterion("last_logintime in", values, "lastLogintime");
            return this;
        }

        public Criteria andLastLogintimeNotIn(List values) {
            addCriterion("last_logintime not in", values, "lastLogintime");
            return this;
        }

        public Criteria andLastLogintimeBetween(Integer value1, Integer value2) {
            addCriterion("last_logintime between", value1, value2, "lastLogintime");
            return this;
        }

        public Criteria andLastLogintimeNotBetween(Integer value1, Integer value2) {
            addCriterion("last_logintime not between", value1, value2, "lastLogintime");
            return this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return this;
        }

        public Criteria andUpdatedAtEqualTo(Integer value) {
            addCriterion("updated_at =", value, "updatedAt");
            return this;
        }

        public Criteria andUpdatedAtNotEqualTo(Integer value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return this;
        }

        public Criteria andUpdatedAtGreaterThan(Integer value) {
            addCriterion("updated_at >", value, "updatedAt");
            return this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Integer value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return this;
        }

        public Criteria andUpdatedAtLessThan(Integer value) {
            addCriterion("updated_at <", value, "updatedAt");
            return this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Integer value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return this;
        }

        public Criteria andUpdatedAtIn(List values) {
            addCriterion("updated_at in", values, "updatedAt");
            return this;
        }

        public Criteria andUpdatedAtNotIn(List values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return this;
        }

        public Criteria andUpdatedAtBetween(Integer value1, Integer value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return this;
        }

        public Criteria andUpdatedAtNotBetween(Integer value1, Integer value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return this;
        }

        public Criteria andCreatedIpIsNull() {
            addCriterion("created_ip is null");
            return this;
        }

        public Criteria andCreatedIpIsNotNull() {
            addCriterion("created_ip is not null");
            return this;
        }

        public Criteria andCreatedIpEqualTo(String value) {
            addCriterion("created_ip =", value, "createdIp");
            return this;
        }

        public Criteria andCreatedIpNotEqualTo(String value) {
            addCriterion("created_ip <>", value, "createdIp");
            return this;
        }

        public Criteria andCreatedIpGreaterThan(String value) {
            addCriterion("created_ip >", value, "createdIp");
            return this;
        }

        public Criteria andCreatedIpGreaterThanOrEqualTo(String value) {
            addCriterion("created_ip >=", value, "createdIp");
            return this;
        }

        public Criteria andCreatedIpLessThan(String value) {
            addCriterion("created_ip <", value, "createdIp");
            return this;
        }

        public Criteria andCreatedIpLessThanOrEqualTo(String value) {
            addCriterion("created_ip <=", value, "createdIp");
            return this;
        }

        public Criteria andCreatedIpLike(String value) {
            addCriterion("created_ip like", value, "createdIp");
            return this;
        }

        public Criteria andCreatedIpNotLike(String value) {
            addCriterion("created_ip not like", value, "createdIp");
            return this;
        }

        public Criteria andCreatedIpIn(List values) {
            addCriterion("created_ip in", values, "createdIp");
            return this;
        }

        public Criteria andCreatedIpNotIn(List values) {
            addCriterion("created_ip not in", values, "createdIp");
            return this;
        }

        public Criteria andCreatedIpBetween(String value1, String value2) {
            addCriterion("created_ip between", value1, value2, "createdIp");
            return this;
        }

        public Criteria andCreatedIpNotBetween(String value1, String value2) {
            addCriterion("created_ip not between", value1, value2, "createdIp");
            return this;
        }

        public Criteria andInviteUseridIsNull() {
            addCriterion("invite_userid is null");
            return this;
        }

        public Criteria andInviteUseridIsNotNull() {
            addCriterion("invite_userid is not null");
            return this;
        }

        public Criteria andInviteUseridEqualTo(Integer value) {
            addCriterion("invite_userid =", value, "inviteUserid");
            return this;
        }

        public Criteria andInviteUseridNotEqualTo(Integer value) {
            addCriterion("invite_userid <>", value, "inviteUserid");
            return this;
        }

        public Criteria andInviteUseridGreaterThan(Integer value) {
            addCriterion("invite_userid >", value, "inviteUserid");
            return this;
        }

        public Criteria andInviteUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("invite_userid >=", value, "inviteUserid");
            return this;
        }

        public Criteria andInviteUseridLessThan(Integer value) {
            addCriterion("invite_userid <", value, "inviteUserid");
            return this;
        }

        public Criteria andInviteUseridLessThanOrEqualTo(Integer value) {
            addCriterion("invite_userid <=", value, "inviteUserid");
            return this;
        }

        public Criteria andInviteUseridIn(List values) {
            addCriterion("invite_userid in", values, "inviteUserid");
            return this;
        }

        public Criteria andInviteUseridNotIn(List values) {
            addCriterion("invite_userid not in", values, "inviteUserid");
            return this;
        }

        public Criteria andInviteUseridBetween(Integer value1, Integer value2) {
            addCriterion("invite_userid between", value1, value2, "inviteUserid");
            return this;
        }

        public Criteria andInviteUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("invite_userid not between", value1, value2, "inviteUserid");
            return this;
        }

        public Criteria andRealVerifyTimeIsNull() {
            addCriterion("real_verify_time is null");
            return this;
        }

        public Criteria andRealVerifyTimeIsNotNull() {
            addCriterion("real_verify_time is not null");
            return this;
        }

        public Criteria andRealVerifyTimeEqualTo(Integer value) {
            addCriterion("real_verify_time =", value, "realVerifyTime");
            return this;
        }

        public Criteria andRealVerifyTimeNotEqualTo(Integer value) {
            addCriterion("real_verify_time <>", value, "realVerifyTime");
            return this;
        }

        public Criteria andRealVerifyTimeGreaterThan(Integer value) {
            addCriterion("real_verify_time >", value, "realVerifyTime");
            return this;
        }

        public Criteria andRealVerifyTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("real_verify_time >=", value, "realVerifyTime");
            return this;
        }

        public Criteria andRealVerifyTimeLessThan(Integer value) {
            addCriterion("real_verify_time <", value, "realVerifyTime");
            return this;
        }

        public Criteria andRealVerifyTimeLessThanOrEqualTo(Integer value) {
            addCriterion("real_verify_time <=", value, "realVerifyTime");
            return this;
        }

        public Criteria andRealVerifyTimeIn(List values) {
            addCriterion("real_verify_time in", values, "realVerifyTime");
            return this;
        }

        public Criteria andRealVerifyTimeNotIn(List values) {
            addCriterion("real_verify_time not in", values, "realVerifyTime");
            return this;
        }

        public Criteria andRealVerifyTimeBetween(Integer value1, Integer value2) {
            addCriterion("real_verify_time between", value1, value2, "realVerifyTime");
            return this;
        }

        public Criteria andRealVerifyTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("real_verify_time not between", value1, value2, "realVerifyTime");
            return this;
        }

        public Criteria andJsessionIdIsNull() {
            addCriterion("jsession_id is null");
            return this;
        }

        public Criteria andJsessionIdIsNotNull() {
            addCriterion("jsession_id is not null");
            return this;
        }

        public Criteria andJsessionIdEqualTo(String value) {
            addCriterion("jsession_id =", value, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdNotEqualTo(String value) {
            addCriterion("jsession_id <>", value, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdGreaterThan(String value) {
            addCriterion("jsession_id >", value, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdGreaterThanOrEqualTo(String value) {
            addCriterion("jsession_id >=", value, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdLessThan(String value) {
            addCriterion("jsession_id <", value, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdLessThanOrEqualTo(String value) {
            addCriterion("jsession_id <=", value, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdLike(String value) {
            addCriterion("jsession_id like", value, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdNotLike(String value) {
            addCriterion("jsession_id not like", value, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdIn(List values) {
            addCriterion("jsession_id in", values, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdNotIn(List values) {
            addCriterion("jsession_id not in", values, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdBetween(String value1, String value2) {
            addCriterion("jsession_id between", value1, value2, "jsessionId");
            return this;
        }

        public Criteria andJsessionIdNotBetween(String value1, String value2) {
            addCriterion("jsession_id not between", value1, value2, "jsessionId");
            return this;
        }

        public Criteria andLuckydrawLoginIsNull() {
            addCriterion("luckydraw_login is null");
            return this;
        }

        public Criteria andLuckydrawLoginIsNotNull() {
            addCriterion("luckydraw_login is not null");
            return this;
        }

        public Criteria andLuckydrawLoginEqualTo(Integer value) {
            addCriterion("luckydraw_login =", value, "luckydrawLogin");
            return this;
        }

        public Criteria andLuckydrawLoginNotEqualTo(Integer value) {
            addCriterion("luckydraw_login <>", value, "luckydrawLogin");
            return this;
        }

        public Criteria andLuckydrawLoginGreaterThan(Integer value) {
            addCriterion("luckydraw_login >", value, "luckydrawLogin");
            return this;
        }

        public Criteria andLuckydrawLoginGreaterThanOrEqualTo(Integer value) {
            addCriterion("luckydraw_login >=", value, "luckydrawLogin");
            return this;
        }

        public Criteria andLuckydrawLoginLessThan(Integer value) {
            addCriterion("luckydraw_login <", value, "luckydrawLogin");
            return this;
        }

        public Criteria andLuckydrawLoginLessThanOrEqualTo(Integer value) {
            addCriterion("luckydraw_login <=", value, "luckydrawLogin");
            return this;
        }

        public Criteria andLuckydrawLoginIn(List values) {
            addCriterion("luckydraw_login in", values, "luckydrawLogin");
            return this;
        }

        public Criteria andLuckydrawLoginNotIn(List values) {
            addCriterion("luckydraw_login not in", values, "luckydrawLogin");
            return this;
        }

        public Criteria andLuckydrawLoginBetween(Integer value1, Integer value2) {
            addCriterion("luckydraw_login between", value1, value2, "luckydrawLogin");
            return this;
        }

        public Criteria andLuckydrawLoginNotBetween(Integer value1, Integer value2) {
            addCriterion("luckydraw_login not between", value1, value2, "luckydrawLogin");
            return this;
        }

        public Criteria andLuckydrawTenderIsNull() {
            addCriterion("luckydraw_tender is null");
            return this;
        }

        public Criteria andLuckydrawTenderIsNotNull() {
            addCriterion("luckydraw_tender is not null");
            return this;
        }

        public Criteria andLuckydrawTenderEqualTo(Integer value) {
            addCriterion("luckydraw_tender =", value, "luckydrawTender");
            return this;
        }

        public Criteria andLuckydrawTenderNotEqualTo(Integer value) {
            addCriterion("luckydraw_tender <>", value, "luckydrawTender");
            return this;
        }

        public Criteria andLuckydrawTenderGreaterThan(Integer value) {
            addCriterion("luckydraw_tender >", value, "luckydrawTender");
            return this;
        }

        public Criteria andLuckydrawTenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("luckydraw_tender >=", value, "luckydrawTender");
            return this;
        }

        public Criteria andLuckydrawTenderLessThan(Integer value) {
            addCriterion("luckydraw_tender <", value, "luckydrawTender");
            return this;
        }

        public Criteria andLuckydrawTenderLessThanOrEqualTo(Integer value) {
            addCriterion("luckydraw_tender <=", value, "luckydrawTender");
            return this;
        }

        public Criteria andLuckydrawTenderIn(List values) {
            addCriterion("luckydraw_tender in", values, "luckydrawTender");
            return this;
        }

        public Criteria andLuckydrawTenderNotIn(List values) {
            addCriterion("luckydraw_tender not in", values, "luckydrawTender");
            return this;
        }

        public Criteria andLuckydrawTenderBetween(Integer value1, Integer value2) {
            addCriterion("luckydraw_tender between", value1, value2, "luckydrawTender");
            return this;
        }

        public Criteria andLuckydrawTenderNotBetween(Integer value1, Integer value2) {
            addCriterion("luckydraw_tender not between", value1, value2, "luckydrawTender");
            return this;
        }

        public Criteria andLogintimesIsNull() {
            addCriterion("loginTimes is null");
            return this;
        }

        public Criteria andLogintimesIsNotNull() {
            addCriterion("loginTimes is not null");
            return this;
        }

        public Criteria andLogintimesEqualTo(Integer value) {
            addCriterion("loginTimes =", value, "logintimes");
            return this;
        }

        public Criteria andLogintimesNotEqualTo(Integer value) {
            addCriterion("loginTimes <>", value, "logintimes");
            return this;
        }

        public Criteria andLogintimesGreaterThan(Integer value) {
            addCriterion("loginTimes >", value, "logintimes");
            return this;
        }

        public Criteria andLogintimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("loginTimes >=", value, "logintimes");
            return this;
        }

        public Criteria andLogintimesLessThan(Integer value) {
            addCriterion("loginTimes <", value, "logintimes");
            return this;
        }

        public Criteria andLogintimesLessThanOrEqualTo(Integer value) {
            addCriterion("loginTimes <=", value, "logintimes");
            return this;
        }

        public Criteria andLogintimesIn(List values) {
            addCriterion("loginTimes in", values, "logintimes");
            return this;
        }

        public Criteria andLogintimesNotIn(List values) {
            addCriterion("loginTimes not in", values, "logintimes");
            return this;
        }

        public Criteria andLogintimesBetween(Integer value1, Integer value2) {
            addCriterion("loginTimes between", value1, value2, "logintimes");
            return this;
        }

        public Criteria andLogintimesNotBetween(Integer value1, Integer value2) {
            addCriterion("loginTimes not between", value1, value2, "logintimes");
            return this;
        }
    }
}