package com.tomcat.dao;

import com.tomcat.model.TbAuthItem;
import com.tomcat.model.TbAuthItemExample;
import com.tomcat.model.TbAuthItemWithBLOBs;
import java.util.List;

public interface TbAuthItemDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int countByExample(TbAuthItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByExample(TbAuthItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insert(TbAuthItemWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insertSelective(TbAuthItemWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExampleWithBLOBs(TbAuthItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExampleWithoutBLOBs(TbAuthItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    TbAuthItemWithBLOBs selectByPrimaryKey(String name);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExampleSelective(TbAuthItemWithBLOBs record, TbAuthItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExample(TbAuthItemWithBLOBs record, TbAuthItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExample(TbAuthItem record, TbAuthItemExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKeySelective(TbAuthItemWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKey(TbAuthItemWithBLOBs record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_auth_item
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKey(TbAuthItem record);
}