package com.tomcat.dao;

import com.tomcat.model.TbBorrowCollection;
import com.tomcat.model.TbBorrowCollectionExample;
import java.util.List;

public interface TbBorrowCollectionDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int countByExample(TbBorrowCollectionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByExample(TbBorrowCollectionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insert(TbBorrowCollection record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    void insertSelective(TbBorrowCollection record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    List selectByExample(TbBorrowCollectionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    TbBorrowCollection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExampleSelective(TbBorrowCollection record, TbBorrowCollectionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByExample(TbBorrowCollection record, TbBorrowCollectionExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKeySelective(TbBorrowCollection record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tb_borrow_collection
     *
     * @ibatorgenerated Fri Dec 09 14:23:08 CST 2016
     */
    int updateByPrimaryKey(TbBorrowCollection record);
}